// Takes a normalized schema model and emits the three generated artifacts:
//   1. supabase/migrations/0002_generated_schema.sql
//   2. tools/generated/schema-map.json   (consumed by migrate-airtable.js)
//   3. web/src/config/entities.json      (consumed by the admin UI)
//
// Model shape:
// {
//   tables: [{
//     airtableId, airtableName, pgName, titleField,
//     columns: [{ airtableName, pgName, pgType, airtableType }],
//     links: [
//       { airtableName, kind: 'fk', pgColumn, targetTable }
//       { airtableName, kind: 'junction', junctionTable, sourceColumn, targetColumn, targetTable }
//     ]
//   }]
// }

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

export function emitAll(model, { generatedBy }) {
  const sqlPath = join(ROOT, 'supabase/migrations/0002_generated_schema.sql');
  const mapPath = join(ROOT, 'tools/generated/schema-map.json');
  const entitiesPath = join(ROOT, 'web/src/config/entities.json');

  writeArtifact(sqlPath, emitSql(model, generatedBy));
  writeArtifact(mapPath, JSON.stringify(model, null, 2) + '\n');
  writeArtifact(entitiesPath, JSON.stringify(emitEntities(model), null, 2) + '\n');

  return [sqlPath, mapPath, entitiesPath];
}

function writeArtifact(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`  wrote ${path.replace(ROOT + '/', '')}`);
}

// ---------------------------------------------------------------------------
// SQL
// ---------------------------------------------------------------------------
function emitSql(model, generatedBy) {
  const out = [];
  out.push(`-- ============================================================================`);
  out.push(`-- 0002_generated_schema.sql — GENERATED by ${generatedBy}. Do not hand-edit;`);
  out.push(`-- re-run the generator instead. Requires 0001_core.sql to be applied first.`);
  out.push(`-- ============================================================================`);

  const allTableNames = [];

  // 1. tables (FK constraints added afterwards so creation order never matters)
  for (const t of model.tables) {
    allTableNames.push(t.pgName);
    out.push('');
    out.push(`-- from Airtable table "${t.airtableName}"`);
    const cols = [
      { def: `id          uuid primary key default gen_random_uuid()` },
      { def: `airtable_id text unique` },
      { def: `source      text` },
      { def: `external_id text` },
    ];
    for (const c of t.columns) {
      cols.push({ def: `${ident(c.pgName)} ${c.pgType}`, comment: `"${c.airtableName}" (${c.airtableType})` });
    }
    for (const l of t.links.filter((l) => l.kind === 'fk')) {
      cols.push({ def: `${ident(l.pgColumn)} uuid`, comment: `link "${l.airtableName}" -> ${l.targetTable}` });
    }
    cols.push({ def: `created_at  timestamptz not null default now()` });
    cols.push({ def: `updated_at  timestamptz not null default now()` });
    const body = cols
      .map((c, i) => `  ${c.def}${i < cols.length - 1 ? ',' : ''}${c.comment ? `  -- ${c.comment}` : ''}`)
      .join('\n');
    out.push(`create table if not exists public.${ident(t.pgName)} (\n${body}\n);`);
    // non-partial so PostgREST upserts can target it; NULL external_ids never collide
    out.push(`create unique index if not exists ${t.pgName}_source_external_idx`);
    out.push(`  on public.${ident(t.pgName)} (source, external_id);`);
  }

  // 2. FK constraints + indexes
  out.push('');
  out.push(`-- ---- foreign keys -------------------------------------------------------`);
  for (const t of model.tables) {
    for (const l of t.links.filter((l) => l.kind === 'fk')) {
      const cname = `${t.pgName}_${l.pgColumn}_fkey`;
      out.push(`alter table public.${ident(t.pgName)} drop constraint if exists ${cname};`);
      out.push(`alter table public.${ident(t.pgName)} add constraint ${cname}`);
      out.push(`  foreign key (${ident(l.pgColumn)}) references public.${ident(l.targetTable)} (id) on delete set null;`);
      out.push(`create index if not exists ${t.pgName}_${l.pgColumn}_idx on public.${ident(t.pgName)} (${ident(l.pgColumn)});`);
    }
  }

  // 3. junction tables for multi-record links
  const junctions = model.tables.flatMap((t) =>
    t.links.filter((l) => l.kind === 'junction').map((l) => ({ ...l, srcTable: t.pgName })),
  );
  if (junctions.length) {
    out.push('');
    out.push(`-- ---- junction tables (multi-record links) --------------------------------`);
    for (const j of junctions) {
      allTableNames.push(j.junctionTable);
      out.push(`create table if not exists public.${ident(j.junctionTable)} (`);
      out.push(`  ${ident(j.sourceColumn)} uuid not null references public.${ident(j.srcTable)} (id) on delete cascade,`);
      out.push(`  ${ident(j.targetColumn)} uuid not null references public.${ident(j.targetTable)} (id) on delete cascade,`);
      out.push(`  primary key (${ident(j.sourceColumn)}, ${ident(j.targetColumn)})`);
      out.push(`);`);
      out.push(`create index if not exists ${j.junctionTable}_target_idx on public.${ident(j.junctionTable)} (${ident(j.targetColumn)});`);
    }
  }

  // 4. updated_at triggers (domain tables only — junctions have no updated_at)
  //    + RLS for everything
  const domainTables = model.tables.map((t) => t.pgName);
  out.push('');
  out.push(`-- ---- triggers + row level security ----------------------------------------`);
  out.push(`do $$`);
  out.push(`declare t text;`);
  out.push(`begin`);
  out.push(`  foreach t in array array[${domainTables.map((n) => `'${n}'`).join(',')}] loop`);
  out.push(`    execute format('drop trigger if exists set_updated_at on public.%I', t);`);
  out.push(`    execute format('create trigger set_updated_at before update on public.%I`);
  out.push(`                    for each row execute function public.set_updated_at()', t);`);
  out.push(`  end loop;`);
  out.push(`  foreach t in array array[${allTableNames.map((n) => `'${n}'`).join(',')}] loop`);
  out.push(`    execute format('alter table public.%I enable row level security', t);`);
  out.push(`    execute format('drop policy if exists "authenticated full access" on public.%I', t);`);
  out.push(`    execute format('create policy "authenticated full access" on public.%I`);
  out.push(`                    for all to authenticated using (true) with check (true)', t);`);
  out.push(`  end loop;`);
  out.push(`end $$;`);
  out.push('');
  return out.join('\n');
}

const ident = (name) => `"${name}"`;

// ---------------------------------------------------------------------------
// entities.json for the admin UI
// ---------------------------------------------------------------------------
function emitEntities(model) {
  const entities = model.tables.map((t) => ({
    table: t.pgName,
    label: t.airtableName,
    titleField: t.titleField,
    columns: [
      ...t.columns.map((c) => ({ name: c.pgName, label: c.airtableName, type: uiType(c.pgType) })),
      { name: 'created_at', label: 'Created', type: 'datetime' },
    ],
    relations: t.links.map((l) =>
      l.kind === 'fk'
        ? { kind: 'belongsTo', label: l.airtableName, table: l.targetTable, fk: l.pgColumn }
        : { kind: 'manyToMany', label: l.airtableName, table: l.targetTable,
            junction: l.junctionTable, sourceColumn: l.sourceColumn, targetColumn: l.targetColumn },
    ),
  }));

  // reverse relations so both sides can navigate (links are stored once)
  const byTable = Object.fromEntries(entities.map((e) => [e.table, e]));
  for (const t of model.tables) {
    for (const l of t.links) {
      if (l.kind === 'fk') {
        byTable[l.targetTable]?.relations.push({
          kind: 'hasMany', label: t.airtableName, table: t.pgName, fk: l.pgColumn,
        });
      } else if (l.targetTable !== t.pgName) {
        byTable[l.targetTable]?.relations.push({
          kind: 'manyToMany', label: t.airtableName, table: t.pgName,
          junction: l.junctionTable, sourceColumn: l.targetColumn, targetColumn: l.sourceColumn,
        });
      }
    }
  }
  return { entities };
}

function uiType(pgType) {
  const base = pgType.replace(/\(.*\)/, '');
  return { 'text': 'text', 'text[]': 'tags', numeric: 'number', integer: 'number',
    boolean: 'boolean', date: 'date', timestamptz: 'datetime', jsonb: 'json' }[base] ?? 'text';
}
