-- ============================================================================
-- 0001_core.sql — infrastructure shared by every schema
-- Apply this BEFORE the generated schema migration.
-- ============================================================================

create extension if not exists "pgcrypto"; -- gen_random_uuid()

-- ---------------------------------------------------------------------------
-- updated_at bookkeeping: every domain table attaches this trigger
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------------------------------------------------------------------------
-- Ingestion audit log: every inbound event (form, booking, payment webhook)
-- lands here first, then gets marked processed/failed. This is the debugging
-- surface that replaces guessing at Zapier task history.
-- ---------------------------------------------------------------------------
create table if not exists public.ingestion_events (
  id           uuid primary key default gen_random_uuid(),
  source       text not null,                 -- e.g. 'typeform', 'calendly', 'stripe'
  event_type   text not null,                 -- e.g. 'form.submitted', 'booking.created'
  external_id  text,                          -- sender's event/delivery id, for replay detection
  payload      jsonb not null,
  status       text not null default 'received'
               check (status in ('received', 'processed', 'failed', 'skipped')),
  error        text,                          -- populated when status = 'failed'
  record_table text,                          -- which table the event wrote to
  record_id    uuid,                          -- and which row
  received_at  timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists ingestion_events_status_idx   on public.ingestion_events (status, received_at desc);
create index if not exists ingestion_events_source_idx   on public.ingestion_events (source, received_at desc);
-- replayed webhook deliveries are detectable per source
create unique index if not exists ingestion_events_external_idx
  on public.ingestion_events (source, external_id) where external_id is not null;

alter table public.ingestion_events enable row level security;

-- Internal single-operator tool: any authenticated user has full access.
-- The ingestion API uses the service-role key, which bypasses RLS entirely.
drop policy if exists "authenticated full access" on public.ingestion_events;
create policy "authenticated full access" on public.ingestion_events
  for all to authenticated using (true) with check (true);
-- ============================================================================
-- 0002_generated_schema.sql — GENERATED by tools/generate-schema.js. Do not hand-edit;
-- re-run the generator instead. Requires 0001_core.sql to be applied first.
-- ============================================================================

-- from Airtable table "Leads"
create table if not exists public."leads" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "lead_name" text,  -- "Lead Name" (singleLineText)
  "email" text,  -- "Email" (email)
  "phone" text,  -- "Phone" (phoneNumber)
  "source_2" text,  -- "Source" (singleSelect)
  "set_by" text,  -- "Set By" (singleSelect)
  "date_added" date,  -- "Date Added" (date)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists leads_source_external_idx
  on public."leads" (source, external_id);

-- from Airtable table "Bookings"
create table if not exists public."bookings" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "booking_id" text,  -- "Booking ID" (formula)
  "start_time" timestamptz,  -- "Start Time" (dateTime)
  "status" text,  -- "Status" (singleSelect)
  "showed_up" boolean,  -- "Showed Up?" (checkbox)
  "closed" boolean,  -- "Closed?" (checkbox)
  "cash_collected" numeric(12,2),  -- "Cash Collected" (currency)
  "revenue_generated" numeric(12,2),  -- "Revenue Generated" (currency)
  "notes" text,  -- "Notes" (multilineText)
  "day_key" text,  -- "Day Key" (formula)
  "week_key" text,  -- "Week Key" (formula)
  "sales_reps" text,  -- "Sales Reps" (singleLineText)
  "form_link" text,  -- "Form Link" (formula)
  "objection" text,  -- "Objection" (singleSelect)
  "fathom_link" text,  -- "Fathom Link" (url)
  "email_from_email" jsonb,  -- "Email (from Email)" (multipleLookupValues)
  "email_calendly" text,  -- "Email - Calendly" (singleLineText)
  "lead_id" uuid,  -- link "Lead Name" -> leads
  "set_by_id" uuid,  -- link "Set By" -> sales_reps
  "closer_id" uuid,  -- link "Closer" -> sales_reps
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists bookings_source_external_idx
  on public."bookings" (source, external_id);

-- from Airtable table "Sales Reps"
create table if not exists public."sales_reps" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "rep_name" text,  -- "Rep Name" (multilineText)
  "email" text,  -- "Email" (email)
  "role" text,  -- "Role" (singleSelect)
  "set" numeric,  -- "Set %" (percent)
  "close" numeric,  -- "Close %" (percent)
  "set_by" integer,  -- "Set By" (count)
  "calls_on_cal" integer,  -- "Calls On Cal" (count)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists sales_reps_source_external_idx
  on public."sales_reps" (source, external_id);

-- from Airtable table "Transactions"
create table if not exists public."transactions" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "transaction_id" text,  -- "Transaction ID" (multilineText)
  "amount" numeric(12,2),  -- "Amount" (currency)
  "date" date,  -- "Date" (date)
  "status" text,  -- "Status" (singleSelect)
  "set_by" jsonb,  -- "Set By" (multipleLookupValues)
  "closed_by" jsonb,  -- "Closed By" (multipleLookupValues)
  "setter_commission" numeric,  -- "Setter Commission" (formula)
  "closer_commission" numeric,  -- "Closer Commission" (formula)
  "day_key" date,  -- "Day Key" (date)
  "week_key" timestamptz,  -- "Week Key" (dateTime)
  "booking_id" uuid,  -- link "Booking" -> bookings
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists transactions_source_external_idx
  on public."transactions" (source, external_id);

-- from Airtable table "Emails"
create table if not exists public."emails" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "campaign_name" text,  -- "Campaign Name" (multilineText)
  "send_date" date,  -- "Send Date" (date)
  "recipients" numeric,  -- "Recipients" (number)
  "open_rate" numeric,  -- "Open Rate" (number)
  "click_rate" numeric,  -- "Click Rate" (number)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists emails_source_external_idx
  on public."emails" (source, external_id);

-- from Airtable table "Setter EOD report"
create table if not exists public."setter_eod_report" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "eod_report_name" text,  -- "EOD Report Name" (singleLineText)
  "date" date,  -- "Date" (date)
  "dials" numeric,  -- "Dials" (number)
  "pickups" numeric,  -- "Pickups" (number)
  "conversations" numeric,  -- "Conversations" (number)
  "booked_calls" numeric,  -- "Booked Calls" (number)
  "cash_collected" numeric(12,2),  -- "Cash collected" (currency)
  "revenue_generated" numeric(12,2),  -- "Revenue generated" (currency)
  "sales_rep_id" uuid,  -- link "Sales Rep" -> sales_reps
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists setter_eod_report_source_external_idx
  on public."setter_eod_report" (source, external_id);

-- ---- foreign keys -------------------------------------------------------
alter table public."bookings" drop constraint if exists bookings_lead_id_fkey;
alter table public."bookings" add constraint bookings_lead_id_fkey
  foreign key ("lead_id") references public."leads" (id) on delete set null;
create index if not exists bookings_lead_id_idx on public."bookings" ("lead_id");
alter table public."bookings" drop constraint if exists bookings_set_by_id_fkey;
alter table public."bookings" add constraint bookings_set_by_id_fkey
  foreign key ("set_by_id") references public."sales_reps" (id) on delete set null;
create index if not exists bookings_set_by_id_idx on public."bookings" ("set_by_id");
alter table public."bookings" drop constraint if exists bookings_closer_id_fkey;
alter table public."bookings" add constraint bookings_closer_id_fkey
  foreign key ("closer_id") references public."sales_reps" (id) on delete set null;
create index if not exists bookings_closer_id_idx on public."bookings" ("closer_id");
alter table public."transactions" drop constraint if exists transactions_booking_id_fkey;
alter table public."transactions" add constraint transactions_booking_id_fkey
  foreign key ("booking_id") references public."bookings" (id) on delete set null;
create index if not exists transactions_booking_id_idx on public."transactions" ("booking_id");
alter table public."setter_eod_report" drop constraint if exists setter_eod_report_sales_rep_id_fkey;
alter table public."setter_eod_report" add constraint setter_eod_report_sales_rep_id_fkey
  foreign key ("sales_rep_id") references public."sales_reps" (id) on delete set null;
create index if not exists setter_eod_report_sales_rep_id_idx on public."setter_eod_report" ("sales_rep_id");

-- ---- triggers + row level security ----------------------------------------
do $$
declare t text;
begin
  foreach t in array array['leads','bookings','sales_reps','transactions','emails','setter_eod_report'] loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format('create trigger set_updated_at before update on public.%I
                    for each row execute function public.set_updated_at()', t);
  end loop;
  foreach t in array array['leads','bookings','sales_reps','transactions','emails','setter_eod_report'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "authenticated full access" on public.%I', t);
    execute format('create policy "authenticated full access" on public.%I
                    for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;
-- ============================================================================
-- 0003_metrics_views.sql — live replacement for the Airtable "Metrics" table.
--
-- In Airtable, Metrics was a table of rollups/formulas that had to be linked
-- to every booking/lead/transaction to work. Here it's computed straight from
-- the source tables, so it can never drift and needs no plumbing.
-- security_invoker makes the views respect the querying user's RLS.
-- ============================================================================

create or replace view public.metrics_weekly
  with (security_invoker = true) as
with b as (
  select date_trunc('week', start_time)::date as wk,
         count(*)                              as total_bookings,
         count(*) filter (where showed_up)     as total_shows,
         count(*) filter (where closed)        as total_closes,
         coalesce(sum(cash_collected), 0)      as cash_collected,
         coalesce(sum(revenue_generated), 0)   as revenue_generated
  from public.bookings
  where start_time is not null
  group by 1
),
l as (
  select date_trunc('week', date_added)::date as wk,
         count(*)                             as new_leads
  from public.leads
  where date_added is not null
  group by 1
),
t as (
  select date_trunc('week', "date")::date as wk,
         coalesce(sum(amount), 0)         as transaction_total
  from public.transactions
  where "date" is not null
  group by 1
)
select
  coalesce(b.wk, l.wk, t.wk)                                          as week,
  coalesce(l.new_leads, 0)                                            as new_leads,
  coalesce(b.total_bookings, 0)                                       as total_bookings,
  coalesce(b.total_shows, 0)                                          as total_shows,
  coalesce(b.total_closes, 0)                                         as total_closes,
  round(100.0 * b.total_shows  / nullif(b.total_bookings, 0), 1)      as show_rate,
  round(100.0 * b.total_closes / nullif(b.total_shows, 0), 1)         as close_rate,
  coalesce(b.cash_collected, 0)                                       as cash_collected,
  coalesce(b.revenue_generated, 0)                                    as revenue_generated,
  coalesce(t.transaction_total, 0)                                    as transaction_total
from b
full join l on l.wk = b.wk
full join t on t.wk = coalesce(b.wk, l.wk)
order by 1 desc;

create or replace view public.metrics_daily
  with (security_invoker = true) as
select
  start_time::date                                                    as day,
  count(*)                                                            as total_bookings,
  count(*) filter (where showed_up)                                   as total_shows,
  count(*) filter (where closed)                                      as total_closes,
  round(100.0 * count(*) filter (where showed_up) / nullif(count(*), 0), 1) as show_rate,
  coalesce(sum(cash_collected), 0)                                    as cash_collected,
  coalesce(sum(revenue_generated), 0)                                 as revenue_generated
from public.bookings
where start_time is not null
group by 1
order by 1 desc;


-- ============================================================================
-- 0004_webhook_fields.sql
-- ============================================================================

-- ============================================================================
-- 0004_webhook_fields.sql — columns the Typeform / Calendly / Whop pipeline needs.
-- Safe to re-run (IF NOT EXISTS).
-- ============================================================================

-- Typeform answers shown on the Leads table / detail panel
alter table public.leads
  add column if not exists form_answers jsonb;

alter table public.leads
  add column if not exists form_response_url text;

-- Calendly tracking.* for setter / closer attribution
alter table public.bookings
  add column if not exists utm jsonb;

comment on column public.leads.form_answers is
  'Latest Typeform (or other form) answers keyed by question title';
comment on column public.leads.form_response_url is
  'Vendor deep-link to the raw form response, when available';
comment on column public.bookings.utm is
  'Calendly tracking UTMs: utm_source/content → set_by, utm_campaign → closer';


-- ============================================================================
-- 0005_booking_contact_fields.sql
-- ============================================================================

-- ============================================================================
-- 0005_booking_contact_fields.sql — denormalized contact on bookings so the
-- table shows lead_name / email / phone like leads (bidirectional with lead_id).
-- Safe to re-run.
-- ============================================================================

alter table public.bookings
  add column if not exists lead_name text;

alter table public.bookings
  add column if not exists email text;

alter table public.bookings
  add column if not exists phone text;

comment on column public.bookings.lead_name is
  'Invitee / lead display name (kept in sync with leads.lead_name)';
comment on column public.bookings.email is
  'Invitee / lead email (kept in sync with leads.email; email_calendly is vendor provenance)';
comment on column public.bookings.phone is
  'Invitee / lead phone (kept in sync with leads.phone)';

-- Backfill from linked leads + legacy email_calendly
update public.bookings b
set
  email     = coalesce(b.email, b.email_calendly, l.email),
  lead_name = coalesce(b.lead_name, l.lead_name),
  phone     = coalesce(b.phone, l.phone)
from public.leads l
where b.lead_id = l.id
  and (
    b.email is null
    or b.lead_name is null
    or b.phone is null
  );

-- Bookings with email_calendly but no lead_id still get an email
update public.bookings
set email = coalesce(email, email_calendly)
where email is null and email_calendly is not null;


-- ============================================================================
-- 0006_identity_matches.sql
-- ============================================================================

-- ============================================================================
-- 0006_identity_matches.sql — flag leads that look like the same person across
-- different emails (shared phone and/or name). Safe to re-run.
-- ============================================================================

alter table public.leads
  add column if not exists possible_duplicate boolean not null default false;

create table if not exists public.identity_matches (
  id            uuid primary key default gen_random_uuid(),
  lead_a_id     uuid not null references public.leads (id) on delete cascade,
  lead_b_id     uuid not null references public.leads (id) on delete cascade,
  match_on      text[] not null default '{}',
  confidence    text not null default 'medium'
                check (confidence in ('high', 'medium', 'low')),
  status        text not null default 'open'
                check (status in ('open', 'confirmed', 'dismissed')),
  details       jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  check (lead_a_id <> lead_b_id),
  check (lead_a_id < lead_b_id)
);

create unique index if not exists identity_matches_pair_uidx
  on public.identity_matches (lead_a_id, lead_b_id);

create index if not exists identity_matches_status_idx
  on public.identity_matches (status, confidence, created_at desc);

create index if not exists identity_matches_lead_a_idx on public.identity_matches (lead_a_id);
create index if not exists identity_matches_lead_b_idx on public.identity_matches (lead_b_id);

drop trigger if exists identity_matches_set_updated_at on public.identity_matches;
create trigger identity_matches_set_updated_at
  before update on public.identity_matches
  for each row execute function public.set_updated_at();

alter table public.identity_matches enable row level security;
drop policy if exists "authenticated full access" on public.identity_matches;
create policy "authenticated full access" on public.identity_matches
  for all to authenticated using (true) with check (true);

comment on table public.identity_matches is
  'Possible same-person pairs across different emails (matched on phone/name)';
comment on column public.leads.possible_duplicate is
  'True when this lead has at least one open identity_matches row';

-- Keep leads.possible_duplicate in sync with open matches
create or replace function public.refresh_lead_duplicate_flags(p_lead_ids uuid[])
returns void language plpgsql as $$
begin
  update public.leads l
  set possible_duplicate = exists (
    select 1 from public.identity_matches m
    where m.status = 'open'
      and (m.lead_a_id = l.id or m.lead_b_id = l.id)
  )
  where l.id = any(p_lead_ids);
end $$;


-- ============================================================================
-- 0007_sales_stats_fields.sql
-- ============================================================================

-- ============================================================================
-- 0007_sales_stats_fields.sql — raw fields needed to track Overview KPIs
-- (Booked Calls, Recordings, Show-Ups, Now Closed, PIFs, Splits, Cash
-- Contracted / Collected, Closer Cancelled). Rates & $/call are derived in
-- the sales_overview_stats view — never store those.
-- Safe to re-run.
-- ============================================================================

-- Recordings: explicit flag (also backfilled from fathom_link)
alter table public.bookings
  add column if not exists has_recording boolean not null default false;

-- Paid in full (vs deposit / payment plan)
alter table public.bookings
  add column if not exists pif boolean not null default false;

-- Split deal (multiple payers / shared close)
alter table public.bookings
  add column if not exists is_split boolean not null default false;

-- Contracted deal size (may differ from cash actually collected)
alter table public.bookings
  add column if not exists cash_contracted numeric(12,2);

-- Closer-side cancel (distinct from invitee/lead cancel in status)
alter table public.bookings
  add column if not exists closer_cancelled boolean not null default false;

-- Optional payment shape for reporting
alter table public.bookings
  add column if not exists payment_type text;
  -- expected values: 'pif' | 'deposit' | 'split' | null

comment on column public.bookings.has_recording is
  'True when a call recording exists (Fathom or other)';
comment on column public.bookings.pif is
  'Paid in full';
comment on column public.bookings.is_split is
  'Split / shared close';
comment on column public.bookings.cash_contracted is
  'Contracted cash amount (deal size); cash_collected is money received';
comment on column public.bookings.closer_cancelled is
  'Cancelled by closer (feeds Closer Cancelled / % KPIs)';
comment on column public.bookings.payment_type is
  'pif | deposit | split';

-- Backfills from existing data
update public.bookings
set has_recording = true
where coalesce(has_recording, false) = false
  and fathom_link is not null
  and length(trim(fathom_link)) > 0;

update public.bookings
set closer_cancelled = true
where coalesce(closer_cancelled, false) = false
  and lower(coalesce(status, '')) in (
    'canceled', 'cancelled', 'closer cancelled', 'closer canceled'
  );

update public.bookings
set cash_contracted = revenue_generated
where cash_contracted is null
  and revenue_generated is not null;

update public.bookings
set pif = true,
    payment_type = coalesce(payment_type, 'pif')
where coalesce(pif, false) = false
  and cash_collected is not null
  and cash_contracted is not null
  and cash_collected >= cash_contracted
  and cash_contracted > 0;

update public.bookings
set payment_type = 'split'
where is_split = true
  and payment_type is null;

-- Live Overview KPIs (filter by start_time in the app / a date CTE as needed)
create or replace view public.sales_overview_stats
  with (security_invoker = true) as
select
  count(*) filter (
    where start_time is not null
      and coalesce(closer_cancelled, false) = false
      and lower(coalesce(status, '')) not in ('canceled', 'cancelled')
  )                                                                   as booked_calls,
  count(*) filter (
    where has_recording
       or (fathom_link is not null and length(trim(fathom_link)) > 0)
  )                                                                   as recordings,
  count(*) filter (where showed_up)                                   as show_ups,
  count(*) filter (where closed)                                      as now_closed,
  count(*) filter (where pif)                                         as pifs,
  count(*) filter (where is_split)                                    as splits_count,
  coalesce(sum(cash_contracted), 0)                                   as cash_contracted,
  coalesce(sum(cash_collected), 0)                                    as new_cash_collected,
  count(*) filter (where closer_cancelled)                            as closer_cancelled,
  round(
    100.0 * count(*) filter (where closer_cancelled)
      / nullif(count(*) filter (where start_time is not null), 0)
  , 1)                                                                as closer_cancelled_pct,
  -- Show-up rate: shows / past non-canceled bookings (excl. future)
  round(
    100.0 * count(*) filter (where showed_up)
      / nullif(
        count(*) filter (
          where start_time is not null
            and start_time < now()
            and coalesce(closer_cancelled, false) = false
            and lower(coalesce(status, '')) not in ('canceled', 'cancelled')
        ), 0)
  , 1)                                                                as show_up_rate,
  -- Book to close %: closes / booked (non-canceled)
  round(
    100.0 * count(*) filter (where closed)
      / nullif(
        count(*) filter (
          where start_time is not null
            and coalesce(closer_cancelled, false) = false
            and lower(coalesce(status, '')) not in ('canceled', 'cancelled')
        ), 0)
  , 1)                                                                as book_to_close_pct,
  round(
    coalesce(sum(cash_collected), 0)
      / nullif(
        count(*) filter (
          where start_time is not null
            and coalesce(closer_cancelled, false) = false
            and lower(coalesce(status, '')) not in ('canceled', 'cancelled')
        ), 0)
  , 0)                                                                as cash_per_booked_call,
  -- "Appt" = showed up
  round(
    coalesce(sum(cash_collected), 0)
      / nullif(count(*) filter (where showed_up), 0)
  , 0)                                                                as cash_per_appt,
  round(
    coalesce(sum(cash_contracted), 0)
      / nullif(count(*) filter (where showed_up), 0)
  , 0)                                                                as cash_contracted_per_appt
from public.bookings;

comment on view public.sales_overview_stats is
  'Overview KPI rollup matching the sales dashboard (counts + derived rates)';
