-- ============================================================================
-- 0001_core.sql — infrastructure shared by every schema
-- Apply this BEFORE the generated schema migration.
-- ============================================================================

create extension if not exists "pgcrypto"; -- gen_random_uuid()

-- ---------------------------------------------------------------------------
-- updated_at bookkeeping: every domain table attaches this trigger
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------------------------------------------------------------------------
-- Ingestion audit log: every inbound event (form, booking, payment webhook)
-- lands here first, then gets marked processed/failed. This is the debugging
-- surface that replaces guessing at Zapier task history.
-- ---------------------------------------------------------------------------
create table if not exists public.ingestion_events (
  id           uuid primary key default gen_random_uuid(),
  source       text not null,                 -- e.g. 'typeform', 'calendly', 'stripe'
  event_type   text not null,                 -- e.g. 'form.submitted', 'booking.created'
  external_id  text,                          -- sender's event/delivery id, for replay detection
  payload      jsonb not null,
  status       text not null default 'received'
               check (status in ('received', 'processed', 'failed', 'skipped')),
  error        text,                          -- populated when status = 'failed'
  record_table text,                          -- which table the event wrote to
  record_id    uuid,                          -- and which row
  received_at  timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists ingestion_events_status_idx   on public.ingestion_events (status, received_at desc);
create index if not exists ingestion_events_source_idx   on public.ingestion_events (source, received_at desc);
-- replayed webhook deliveries are detectable per source
create unique index if not exists ingestion_events_external_idx
  on public.ingestion_events (source, external_id) where external_id is not null;

alter table public.ingestion_events enable row level security;

-- Internal single-operator tool: any authenticated user has full access.
-- The ingestion API uses the service-role key, which bypasses RLS entirely.
drop policy if exists "authenticated full access" on public.ingestion_events;
create policy "authenticated full access" on public.ingestion_events
  for all to authenticated using (true) with check (true);
-- ============================================================================
-- 0002_generated_schema.sql — GENERATED by tools/generate-schema.js. Do not hand-edit;
-- re-run the generator instead. Requires 0001_core.sql to be applied first.
-- ============================================================================

-- from Airtable table "Leads"
create table if not exists public."leads" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "lead_name" text,  -- "Lead Name" (singleLineText)
  "email" text,  -- "Email" (email)
  "phone" text,  -- "Phone" (phoneNumber)
  "source_2" text,  -- "Source" (singleSelect)
  "set_by" text,  -- "Set By" (singleSelect)
  "date_added" date,  -- "Date Added" (date)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists leads_source_external_idx
  on public."leads" (source, external_id);

-- from Airtable table "Bookings"
create table if not exists public."bookings" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "booking_id" text,  -- "Booking ID" (formula)
  "start_time" timestamptz,  -- "Start Time" (dateTime)
  "status" text,  -- "Status" (singleSelect)
  "showed_up" boolean,  -- "Showed Up?" (checkbox)
  "closed" boolean,  -- "Closed?" (checkbox)
  "cash_collected" numeric(12,2),  -- "Cash Collected" (currency)
  "revenue_generated" numeric(12,2),  -- "Revenue Generated" (currency)
  "notes" text,  -- "Notes" (multilineText)
  "day_key" text,  -- "Day Key" (formula)
  "week_key" text,  -- "Week Key" (formula)
  "sales_reps" text,  -- "Sales Reps" (singleLineText)
  "form_link" text,  -- "Form Link" (formula)
  "objection" text,  -- "Objection" (singleSelect)
  "fathom_link" text,  -- "Fathom Link" (url)
  "email_from_email" jsonb,  -- "Email (from Email)" (multipleLookupValues)
  "email_calendly" text,  -- "Email - Calendly" (singleLineText)
  "lead_id" uuid,  -- link "Lead Name" -> leads
  "set_by_id" uuid,  -- link "Set By" -> sales_reps
  "closer_id" uuid,  -- link "Closer" -> sales_reps
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists bookings_source_external_idx
  on public."bookings" (source, external_id);

-- from Airtable table "Sales Reps"
create table if not exists public."sales_reps" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "rep_name" text,  -- "Rep Name" (multilineText)
  "email" text,  -- "Email" (email)
  "role" text,  -- "Role" (singleSelect)
  "set" numeric,  -- "Set %" (percent)
  "close" numeric,  -- "Close %" (percent)
  "set_by" integer,  -- "Set By" (count)
  "calls_on_cal" integer,  -- "Calls On Cal" (count)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists sales_reps_source_external_idx
  on public."sales_reps" (source, external_id);

-- from Airtable table "Transactions"
create table if not exists public."transactions" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "transaction_id" text,  -- "Transaction ID" (multilineText)
  "amount" numeric(12,2),  -- "Amount" (currency)
  "date" date,  -- "Date" (date)
  "status" text,  -- "Status" (singleSelect)
  "set_by" jsonb,  -- "Set By" (multipleLookupValues)
  "closed_by" jsonb,  -- "Closed By" (multipleLookupValues)
  "setter_commission" numeric,  -- "Setter Commission" (formula)
  "closer_commission" numeric,  -- "Closer Commission" (formula)
  "day_key" date,  -- "Day Key" (date)
  "week_key" timestamptz,  -- "Week Key" (dateTime)
  "booking_id" uuid,  -- link "Booking" -> bookings
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists transactions_source_external_idx
  on public."transactions" (source, external_id);

-- from Airtable table "Emails"
create table if not exists public."emails" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "campaign_name" text,  -- "Campaign Name" (multilineText)
  "send_date" date,  -- "Send Date" (date)
  "recipients" numeric,  -- "Recipients" (number)
  "open_rate" numeric,  -- "Open Rate" (number)
  "click_rate" numeric,  -- "Click Rate" (number)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists emails_source_external_idx
  on public."emails" (source, external_id);

-- from Airtable table "Setter EOD report"
create table if not exists public."setter_eod_report" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "eod_report_name" text,  -- "EOD Report Name" (singleLineText)
  "date" date,  -- "Date" (date)
  "dials" numeric,  -- "Dials" (number)
  "pickups" numeric,  -- "Pickups" (number)
  "conversations" numeric,  -- "Conversations" (number)
  "booked_calls" numeric,  -- "Booked Calls" (number)
  "cash_collected" numeric(12,2),  -- "Cash collected" (currency)
  "revenue_generated" numeric(12,2),  -- "Revenue generated" (currency)
  "sales_rep_id" uuid,  -- link "Sales Rep" -> sales_reps
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists setter_eod_report_source_external_idx
  on public."setter_eod_report" (source, external_id);

-- ---- foreign keys -------------------------------------------------------
alter table public."bookings" drop constraint if exists bookings_lead_id_fkey;
alter table public."bookings" add constraint bookings_lead_id_fkey
  foreign key ("lead_id") references public."leads" (id) on delete set null;
create index if not exists bookings_lead_id_idx on public."bookings" ("lead_id");
alter table public."bookings" drop constraint if exists bookings_set_by_id_fkey;
alter table public."bookings" add constraint bookings_set_by_id_fkey
  foreign key ("set_by_id") references public."sales_reps" (id) on delete set null;
create index if not exists bookings_set_by_id_idx on public."bookings" ("set_by_id");
alter table public."bookings" drop constraint if exists bookings_closer_id_fkey;
alter table public."bookings" add constraint bookings_closer_id_fkey
  foreign key ("closer_id") references public."sales_reps" (id) on delete set null;
create index if not exists bookings_closer_id_idx on public."bookings" ("closer_id");
alter table public."transactions" drop constraint if exists transactions_booking_id_fkey;
alter table public."transactions" add constraint transactions_booking_id_fkey
  foreign key ("booking_id") references public."bookings" (id) on delete set null;
create index if not exists transactions_booking_id_idx on public."transactions" ("booking_id");
alter table public."setter_eod_report" drop constraint if exists setter_eod_report_sales_rep_id_fkey;
alter table public."setter_eod_report" add constraint setter_eod_report_sales_rep_id_fkey
  foreign key ("sales_rep_id") references public."sales_reps" (id) on delete set null;
create index if not exists setter_eod_report_sales_rep_id_idx on public."setter_eod_report" ("sales_rep_id");

-- ---- triggers + row level security ----------------------------------------
do $$
declare t text;
begin
  foreach t in array array['leads','bookings','sales_reps','transactions','emails','setter_eod_report'] loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format('create trigger set_updated_at before update on public.%I
                    for each row execute function public.set_updated_at()', t);
  end loop;
  foreach t in array array['leads','bookings','sales_reps','transactions','emails','setter_eod_report'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "authenticated full access" on public.%I', t);
    execute format('create policy "authenticated full access" on public.%I
                    for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;
-- ============================================================================
-- 0003_metrics_views.sql — live replacement for the Airtable "Metrics" table.
--
-- In Airtable, Metrics was a table of rollups/formulas that had to be linked
-- to every booking/lead/transaction to work. Here it's computed straight from
-- the source tables, so it can never drift and needs no plumbing.
-- security_invoker makes the views respect the querying user's RLS.
-- ============================================================================

create or replace view public.metrics_weekly
  with (security_invoker = true) as
with b as (
  select date_trunc('week', start_time)::date as wk,
         count(*)                              as total_bookings,
         count(*) filter (where showed_up)     as total_shows,
         count(*) filter (where closed)        as total_closes,
         coalesce(sum(cash_collected), 0)      as cash_collected,
         coalesce(sum(revenue_generated), 0)   as revenue_generated
  from public.bookings
  where start_time is not null
  group by 1
),
l as (
  select date_trunc('week', date_added)::date as wk,
         count(*)                             as new_leads
  from public.leads
  where date_added is not null
  group by 1
),
t as (
  select date_trunc('week', "date")::date as wk,
         coalesce(sum(amount), 0)         as transaction_total
  from public.transactions
  where "date" is not null
  group by 1
)
select
  coalesce(b.wk, l.wk, t.wk)                                          as week,
  coalesce(l.new_leads, 0)                                            as new_leads,
  coalesce(b.total_bookings, 0)                                       as total_bookings,
  coalesce(b.total_shows, 0)                                          as total_shows,
  coalesce(b.total_closes, 0)                                         as total_closes,
  round(100.0 * b.total_shows  / nullif(b.total_bookings, 0), 1)      as show_rate,
  round(100.0 * b.total_closes / nullif(b.total_shows, 0), 1)         as close_rate,
  coalesce(b.cash_collected, 0)                                       as cash_collected,
  coalesce(b.revenue_generated, 0)                                    as revenue_generated,
  coalesce(t.transaction_total, 0)                                    as transaction_total
from b
full join l on l.wk = b.wk
full join t on t.wk = coalesce(b.wk, l.wk)
order by 1 desc;

create or replace view public.metrics_daily
  with (security_invoker = true) as
select
  start_time::date                                                    as day,
  count(*)                                                            as total_bookings,
  count(*) filter (where showed_up)                                   as total_shows,
  count(*) filter (where closed)                                      as total_closes,
  round(100.0 * count(*) filter (where showed_up) / nullif(count(*), 0), 1) as show_rate,
  coalesce(sum(cash_collected), 0)                                    as cash_collected,
  coalesce(sum(revenue_generated), 0)                                 as revenue_generated
from public.bookings
where start_time is not null
group by 1
order by 1 desc;
