-- ============================================================================
-- 0002_generated_schema.sql — GENERATED by tools/generate-schema.js. Do not hand-edit;
-- re-run the generator instead. Requires 0001_core.sql to be applied first.
-- ============================================================================

-- from Airtable table "Leads"
create table if not exists public."leads" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "lead_name" text,  -- "Lead Name" (singleLineText)
  "email" text,  -- "Email" (email)
  "phone" text,  -- "Phone" (phoneNumber)
  "source_2" text,  -- "Source" (singleSelect)
  "set_by" text,  -- "Set By" (singleSelect)
  "date_added" date,  -- "Date Added" (date)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists leads_source_external_idx
  on public."leads" (source, external_id);

-- from Airtable table "Bookings"
create table if not exists public."bookings" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "booking_id" text,  -- "Booking ID" (formula)
  "start_time" timestamptz,  -- "Start Time" (dateTime)
  "status" text,  -- "Status" (singleSelect)
  "showed_up" boolean,  -- "Showed Up?" (checkbox)
  "closed" boolean,  -- "Closed?" (checkbox)
  "cash_collected" numeric(12,2),  -- "Cash Collected" (currency)
  "revenue_generated" numeric(12,2),  -- "Revenue Generated" (currency)
  "notes" text,  -- "Notes" (multilineText)
  "day_key" text,  -- "Day Key" (formula)
  "week_key" text,  -- "Week Key" (formula)
  "sales_reps" text,  -- "Sales Reps" (singleLineText)
  "form_link" text,  -- "Form Link" (formula)
  "objection" text,  -- "Objection" (singleSelect)
  "fathom_link" text,  -- "Fathom Link" (url)
  "email_from_email" jsonb,  -- "Email (from Email)" (multipleLookupValues)
  "email_calendly" text,  -- "Email - Calendly" (singleLineText)
  "lead_id" uuid,  -- link "Lead Name" -> leads
  "set_by_id" uuid,  -- link "Set By" -> sales_reps
  "closer_id" uuid,  -- link "Closer" -> sales_reps
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists bookings_source_external_idx
  on public."bookings" (source, external_id);

-- from Airtable table "Sales Reps"
create table if not exists public."sales_reps" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "rep_name" text,  -- "Rep Name" (multilineText)
  "email" text,  -- "Email" (email)
  "role" text,  -- "Role" (singleSelect)
  "set" numeric,  -- "Set %" (percent)
  "close" numeric,  -- "Close %" (percent)
  "set_by" integer,  -- "Set By" (count)
  "calls_on_cal" integer,  -- "Calls On Cal" (count)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists sales_reps_source_external_idx
  on public."sales_reps" (source, external_id);

-- from Airtable table "Transactions"
create table if not exists public."transactions" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "transaction_id" text,  -- "Transaction ID" (multilineText)
  "amount" numeric(12,2),  -- "Amount" (currency)
  "date" date,  -- "Date" (date)
  "status" text,  -- "Status" (singleSelect)
  "set_by" jsonb,  -- "Set By" (multipleLookupValues)
  "closed_by" jsonb,  -- "Closed By" (multipleLookupValues)
  "setter_commission" numeric,  -- "Setter Commission" (formula)
  "closer_commission" numeric,  -- "Closer Commission" (formula)
  "day_key" date,  -- "Day Key" (date)
  "week_key" timestamptz,  -- "Week Key" (dateTime)
  "booking_id" uuid,  -- link "Booking" -> bookings
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists transactions_source_external_idx
  on public."transactions" (source, external_id);

-- from Airtable table "Emails"
create table if not exists public."emails" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "campaign_name" text,  -- "Campaign Name" (multilineText)
  "send_date" date,  -- "Send Date" (date)
  "recipients" numeric,  -- "Recipients" (number)
  "open_rate" numeric,  -- "Open Rate" (number)
  "click_rate" numeric,  -- "Click Rate" (number)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists emails_source_external_idx
  on public."emails" (source, external_id);

-- from Airtable table "Setter EOD report"
create table if not exists public."setter_eod_report" (
  id          uuid primary key default gen_random_uuid(),
  airtable_id text unique,
  source      text,
  external_id text,
  "eod_report_name" text,  -- "EOD Report Name" (singleLineText)
  "date" date,  -- "Date" (date)
  "dials" numeric,  -- "Dials" (number)
  "pickups" numeric,  -- "Pickups" (number)
  "conversations" numeric,  -- "Conversations" (number)
  "booked_calls" numeric,  -- "Booked Calls" (number)
  "cash_collected" numeric(12,2),  -- "Cash collected" (currency)
  "revenue_generated" numeric(12,2),  -- "Revenue generated" (currency)
  "sales_rep_id" uuid,  -- link "Sales Rep" -> sales_reps
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists setter_eod_report_source_external_idx
  on public."setter_eod_report" (source, external_id);

-- ---- foreign keys -------------------------------------------------------
alter table public."bookings" drop constraint if exists bookings_lead_id_fkey;
alter table public."bookings" add constraint bookings_lead_id_fkey
  foreign key ("lead_id") references public."leads" (id) on delete set null;
create index if not exists bookings_lead_id_idx on public."bookings" ("lead_id");
alter table public."bookings" drop constraint if exists bookings_set_by_id_fkey;
alter table public."bookings" add constraint bookings_set_by_id_fkey
  foreign key ("set_by_id") references public."sales_reps" (id) on delete set null;
create index if not exists bookings_set_by_id_idx on public."bookings" ("set_by_id");
alter table public."bookings" drop constraint if exists bookings_closer_id_fkey;
alter table public."bookings" add constraint bookings_closer_id_fkey
  foreign key ("closer_id") references public."sales_reps" (id) on delete set null;
create index if not exists bookings_closer_id_idx on public."bookings" ("closer_id");
alter table public."transactions" drop constraint if exists transactions_booking_id_fkey;
alter table public."transactions" add constraint transactions_booking_id_fkey
  foreign key ("booking_id") references public."bookings" (id) on delete set null;
create index if not exists transactions_booking_id_idx on public."transactions" ("booking_id");
alter table public."setter_eod_report" drop constraint if exists setter_eod_report_sales_rep_id_fkey;
alter table public."setter_eod_report" add constraint setter_eod_report_sales_rep_id_fkey
  foreign key ("sales_rep_id") references public."sales_reps" (id) on delete set null;
create index if not exists setter_eod_report_sales_rep_id_idx on public."setter_eod_report" ("sales_rep_id");

-- ---- triggers + row level security ----------------------------------------
do $$
declare t text;
begin
  foreach t in array array['leads','bookings','sales_reps','transactions','emails','setter_eod_report'] loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format('create trigger set_updated_at before update on public.%I
                    for each row execute function public.set_updated_at()', t);
  end loop;
  foreach t in array array['leads','bookings','sales_reps','transactions','emails','setter_eod_report'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "authenticated full access" on public.%I', t);
    execute format('create policy "authenticated full access" on public.%I
                    for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;
